### ISSUE TITLE
Are `${foo}Disable` functions needed?

### ISSUE THREAD

**Issue by miketaylr** [mozilla-extensions/webcompat-addon#123]
Right now we have 2 (3, once https://github.com/mozilla/webcompat-addon/pull/122 lands) custom functions that have a `Disable` counterpart that do the same thing.

Should this just be baked into the `disableCustomInjections` code? Or, perhaps, if it's missing, default to what we're doing 3 times now?

```
detectSwipeFixDisable: injection => {
    const { listener } = injection.data;
    browser.webRequest.onHeadersReceived.removeListener(listener);
    delete injection.data.listener;
  },
```

https://github.com/mozilla/webcompat-addon/blob/master/src/lib/custom_functions.js#L51

Also, there's no documentation on this stuff, right?

@denschub @wisniewskit @ksy36

**Comment by ksy36** [comment]
My initial idea was that a custom function can do anything, not necessarily modify a request. So "disable" function is also custom. So `noSniffFixDisable` and `pdk5fixDisable` are a bit different (first one removes listener from `browser.webRequest.onHeadersReceived`, second one from `browser.webRequest.onBeforeRequest`). We could perhaps create a utility function that will accept a callback, something like: 

```js
const rm = (injection, cb) => {
  const { listener } = injection.data;
   cb (listener)
   delete injection.data.listener;
}

noSniffFixDisable: injection => {
 rm(injection, listener => browser.webRequest.onHeadersReceived.removeListener(listener))
},
```

**Comment by denschub** [comment]
The answer to the original question is "yes, we need disable functions". Looking at the current usage, I do not thing it's worth the effort to add another function that abstracts away the three lines of code that is kinda duplicated, especially since it makes the code less understandable. However, if someone feels differently, I'm happy to reconsider my opinion in exchange for cookies.

To avoid confusion and to document the requirements, I [added a section to the already existing docs in the wiki](https://wiki.mozilla.org/index.php?title=Compatibility%2FSystem_Addon%2FOverride_Policies_and_Workflows&type=revision&diff=1230818&oldid=1230558), and so, I'll close this bug as both parts of the issue have been addressed!
