### ISSUE TITLE
Migrate to mozilla-extensions repo

### ISSUE THREAD

**Issue by miketaylr** [mozilla-extensions/webcompat-addon#133]
Right now this is just a placeholder, but I think we will need to update how we build the addon (using `npx web-ext build --source-dir src/ --ignore-files moz.build`), or at least support that.

More info here:

https://github.com/mozilla-extensions/xpi-manifest/blob/master/docs/adding-a-new-xpi.md
https://github.com/mozilla-extensions/xpi-manifest/blob/master/docs/releasing-a-xpi.md

**Comment by denschub** [comment]
During that transition, it's probably also a very good idea to rename the `master` branch to `main`, or something more descriptive. People have to fix their local development setups either way, so doing that change won't cause any additional harm. Also, we have to adjust tooling either way, so doing that at the same time is smart.

**Comment by denschub** [comment]
This is done. Branch names didn't change because that would ruin the taskcluster template, so this has to wait until a future point.

An email highlighting the important changes [has been sent to the compat mailing list](https://groups.google.com/d/msg/mozilla.compatibility/qYO6Zpq9ViE/3MEx9bGxAwAJ), and I upgraded all pieces of documentation I could find.
